/*
 * luci-theme-shadcnui — sidebar.js
 * Handles the collapsed/expanded sidebar state on desktop, the slide-in
 * drawer on mobile, and expand/collapse of nav sections.
 */
(function () {
  'use strict';

  var LS_KEY = 'shadcnui:sidebar';
  var app = document.getElementById('shadcn-app');
  if (!app) return;

  function isMobile() { return window.matchMedia('(max-width: 768px)').matches; }

  function applyState(state) {
    // state: 'expanded' | 'collapsed' | 'open' (mobile)
    app.setAttribute('data-sidebar', state);
  }

  function loadState() {
    try { return localStorage.getItem(LS_KEY) || 'expanded'; }
    catch (e) { return 'expanded'; }
  }
  function saveState(s) {
    try { localStorage.setItem(LS_KEY, s); } catch (e) {}
  }

  // initial state
  applyState(isMobile() ? 'closed' : loadState());

  // toggle button in topbar
  var toggle = document.getElementById('shadcn-sidebar-toggle');
  if (toggle) {
    toggle.addEventListener('click', function (e) {
      e.preventDefault();
      var current = app.getAttribute('data-sidebar') || 'expanded';
      var next;
      if (isMobile()) {
        next = current === 'open' ? 'closed' : 'open';
      } else {
        next = current === 'collapsed' ? 'expanded' : 'collapsed';
        saveState(next);
      }
      applyState(next);
    });
  }

  // tap on overlay closes drawer on mobile
  app.addEventListener('click', function (e) {
    if (!isMobile()) return;
    if (app.getAttribute('data-sidebar') !== 'open') return;
    // overlay is generated by ::after on #shadcn-app — clicks outside #shadcn-sidebar trigger close
    var sidebar = document.getElementById('shadcn-sidebar');
    if (sidebar && !sidebar.contains(e.target) && !toggle.contains(e.target)) {
      applyState('closed');
    }
  });

  // expand/collapse sections
  document.querySelectorAll('.sidebar-toggle').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var section = btn.closest('.sidebar-section');
      if (!section) return;
      var open = section.getAttribute('data-open') === 'true';
      section.setAttribute('data-open', open ? 'false' : 'true');
    });
  });

  // mark active link based on current path; expand its parent section
  var here = location.pathname.replace(/\/+$/, '');
  document.querySelectorAll('.sidebar-link').forEach(function (a) {
    var href = a.getAttribute('href');
    if (!href) return;
    var path = href.replace(/\/+$/, '');
    if (here === path || here.indexOf(path + '/') === 0) {
      a.classList.add('active');
      var sect = a.closest('.sidebar-section');
      if (sect) sect.setAttribute('data-open', 'true');
    }
  });

  // re-evaluate state on resize crossing the breakpoint
  var lastMobile = isMobile();
  window.addEventListener('resize', function () {
    var mob = isMobile();
    if (mob === lastMobile) return;
    lastMobile = mob;
    applyState(mob ? 'closed' : loadState());
  });
})();
