#
# Copyright (C) 2026 bsatou
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=shadcn/ui Theme for LuCI
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

PKG_NAME:=luci-theme-shadcnui
PKG_VERSION:=0.2.2
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=bsatou

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
